
###############################################################################
#
# Inclusive Makefile for the arm64_delta_b30ge6x1 module.
#
# Autogenerated 2022-02-03 14:26:10.485397
#
###############################################################################
arm64_delta_b30ge6x1_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(arm64_delta_b30ge6x1_BASEDIR)module/make.mk
include $(arm64_delta_b30ge6x1_BASEDIR)module/src/make.mk
include $(arm64_delta_b30ge6x1_BASEDIR)module/auto/make.mk

